AWSTemplateFormatVersion: "2010-09-09"
Description: "DNS - Serverless - TodoApp"

Parameters:
  DomainName:
    Type: String
    Description: The domain name for our site, e.g. `my.example.com`
  HostedZoneName:
    Type: String
    Description: The hosted zone name, e.g. `example.com`
  ApiGatewayDomain:
    Type: String
    Default: "d-s61xacoq5b.execute-api.ap-southeast-2.amazonaws.com"

Resources:
  RecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Name: !Ref DomainName
      Comment: !Sub "API (${DomainName})"
      HostedZoneName: !Ref HostedZoneName
      AliasTarget:
        DNSName: !Ref "ApiGatewayDomain"
        HostedZoneId: "Z2RPCDW04V8134" # https://docs.aws.amazon.com/general/latest/gr/rande.html
        EvaluateTargetHealth: false
      Type: A
